;;; fuji-configure.el --- Configuration wizard for Fuji -*- lexical-binding: t; -*-

;; Copyright (C) 2025 ruanxiang
;; Author: ruanxiang
;; Keywords: convenience

;;; Commentary:
;; Two-tier configuration system for Fuji:
;; - Tier 1: Tool Selection (which extractors/backends to use)
;; - Tier 2: Tool-Specific Configuration (paths, credentials, etc.)

;;; Code:

(require 'fuji-extractor)
(require 'fuji-rag)

(declare-function fuji--get-auth "fuji")
(declare-function fuji--save-auth-entry "fuji")
(declare-function fuji--register-mcp-server "fuji")
(declare-function fuji-apply-proxy "fuji")

;;; Auto-detection Functions

(defun fuji--auto-detect-pdftotext ()
  "Auto-detect pdftotext binary path."
  (or (bound-and-true-p fuji-pdftotext-executable)
      (executable-find "pdftotext")))

(defun fuji--auto-detect-marker ()
  "Auto-detect Marker binary path."
  (or (bound-and-true-p fuji-marker-executable)
      (executable-find "marker_single")
      (executable-find "marker")))

(defun fuji--auto-detect-pandoc ()
  "Auto-detect pandoc binary path."
  (or (bound-and-true-p fuji-pandoc-executable)
      (executable-find "pandoc")))

(defun fuji--auto-detect-chrome ()
  "Auto-detect Google Chrome or Chromium binary path."
  (or (bound-and-true-p fuji-chrome-executable)
      (executable-find "google-chrome-stable")
      (executable-find "google-chrome")
      (executable-find "chromium")
      (executable-find "chromium-browser")
      (executable-find "chrome")))

(defun fuji--get-originals-dir ()
  "Get the originals archive directory path."
  (or (bound-and-true-p fuji-originals-archive-dir)
      (expand-file-name "originals/" 
                        (or (bound-and-true-p fuji-cache-directory)
                            (expand-file-name "fuji-cache/" user-emacs-directory)))))

;;; Local Configuration File Management

(defvar fuji-local-config-file 
  (expand-file-name "fuji-local-config.el" user-emacs-directory)
  "Local machine-specific configuration file for Fuji.
This file should NOT be synced to cloud (add to .gitignore).")

(defun fuji--load-local-config ()
  "Load configuration from local config file."
  (when (file-exists-p fuji-local-config-file)
    (load fuji-local-config-file nil t)))

(defun fuji--save-local-config (config-alist)
  "Save CONFIG-ALIST to local config file.
CONFIG-ALIST is an alist of (symbol . value) pairs."
  (with-temp-file fuji-local-config-file
    (insert ";;; Fuji Local Configuration -*- lexical-binding: t; -*-\n")
    (insert ";; This file is auto-generated by fuji-configure\n")
    (insert ";; DO NOT edit manually\n")
    (insert ";; DO NOT sync to cloud (add to .gitignore)\n\n")
    (dolist (item config-alist)
      (insert (format "(setq %s %S)\n" (car item) (cdr item))))
    (insert "\n;;; fuji-local-config.el ends here\n"))
  (message "Fuji: Configuration saved to %s" fuji-local-config-file))

(defun fuji-migrate-config ()
  "Migrate configuration from custom-file to local config file.
This is a one-time migration for existing users."
  (interactive)
  (let ((config-items '()))
    ;; Extract current values if they exist
    (when (boundp 'fuji-marker-executable)
      (push (cons 'fuji-marker-executable fuji-marker-executable) config-items))
    (when (boundp 'fuji-pdftotext-executable)
      (push (cons 'fuji-pdftotext-executable fuji-pdftotext-executable) config-items))
    (when (boundp 'fuji-pandoc-executable)
      (push (cons 'fuji-pandoc-executable fuji-pandoc-executable) config-items))
    (when (boundp 'fuji-cache-directory)
      (push (cons 'fuji-cache-directory fuji-cache-directory) config-items))
    (when (boundp 'fuji-originals-archive-dir)
      (push (cons 'fuji-originals-archive-dir fuji-originals-archive-dir) config-items))
    (when (boundp 'fuji-llm-extraction-tool)
      (push (cons 'fuji-llm-extraction-tool fuji-llm-extraction-tool) config-items))
    (when (boundp 'fuji-docx-extractor)
      (push (cons 'fuji-docx-extractor fuji-docx-extractor) config-items))
    (when (boundp 'fuji-rag-backend-name)
      (push (cons 'fuji-rag-backend-name fuji-rag-backend-name) config-items))
    (when (boundp 'fuji-graphlit-environment-id)
      (push (cons 'fuji-graphlit-environment-id fuji-graphlit-environment-id) config-items))
    (when (boundp 'fuji-http-proxy)
      (push (cons 'fuji-http-proxy fuji-http-proxy) config-items))
    (when (boundp 'fuji-gptel-backend)
      (push (cons 'fuji-gptel-backend fuji-gptel-backend) config-items))
    (when (boundp 'fuji-gptel-model)
      (push (cons 'fuji-gptel-model fuji-gptel-model) config-items))
    (when (boundp 'fuji-gptel-vision-backend)
      (push (cons 'fuji-gptel-vision-backend fuji-gptel-vision-backend) config-items))
    (when (boundp 'fuji-gptel-vision-model)
      (push (cons 'fuji-gptel-vision-model fuji-gptel-vision-model) config-items))
    (when (boundp 'fuji-chrome-executable)
      (push (cons 'fuji-chrome-executable fuji-chrome-executable) config-items))
    
    (if config-items
        (progn
          (fuji--save-local-config config-items)
          (message "Fuji: Migrated %d configuration items to %s" 
                   (length config-items) fuji-local-config-file)
          (message "You can now remove Fuji settings from your custom-file"))
      (message "Fuji: No configuration found to migrate"))))


;;; Tier 1: Tool Selection

(defun fuji-configure-tier1 ()
  "Configure tool selection (Tier 1).
Note: Both pdftotext and LLM tool will be configured.
Returns a plist with selections."
  (interactive)
  (message "=== Fuji Configuration: Tier 1 - Tool Selection ===")
  (message "")
  (message "PDF Extraction Tools:")
  (message "  - pdftotext: Always configured (fast, lightweight, default)")
  (message "  - LLM tool: Also configured (high-quality, with figures)")
  (message "")
  (message "At runtime (fuji-read), you can choose which tool to use.")
  (message "")
  
  (if (featurep 'doi-utils)
      (message "Org-Ref Integration: ✅ Detected (doi-utils loaded)")
    (message "Org-Ref Integration: ❌ Not detected (install org-ref for BibTeX features)"))

  (message "")
  (message "RAG/MCP Backend (for knowledge retrieval):")
  (message "  - graphlit: Cloud-based RAG via MCP (requires credentials)")
  (message "  - local-vector: Future local vector database option")
  (message "")
  
  (let* (;; Ask which LLM tool to configure
         (llm-tool (completing-read
                    "LLM extraction tool (more tools will be added): "
                    '("marker")
                    nil t))
         (llm-tool-value "marker")  ;; Only marker for now
         (docx-extractor (completing-read
                          "DOCX/EPUB/HTML Extractor: "
                          '("pandoc")
                          nil t (or (bound-and-true-p fuji-docx-extractor) "pandoc")))
         (rag-backend (completing-read
                       "RAG/MCP Backend (more backends will be supported): "
                       '("graphlit")
                       nil t))
         (rag-backend-value "graphlit"))  ;; Only graphlit for now
    
    (message "Fuji: Tool selection complete.")
    (message "  pdftotext: Will be configured (always)")
    (message "  LLM Tool: %s" llm-tool-value)
    (message "  DOCX Extractor: %s" docx-extractor)
    (message "  RAG/MCP Backend: %s" rag-backend-value)
    
    ;; Return selections for tier2 to save
    (list :llm-tool llm-tool-value
          :docx-extractor docx-extractor
          :rag-backend rag-backend-value)))

;;; Tier 2: Tool-Specific Configuration

(defun fuji-configure-tier2 ()
  "Configure tool-specific settings (Tier 2) based on Tier 1 selections.
Returns an alist of configured items to be saved."
  (interactive)
  (let ((config-items '())  ;; Collect all config as (symbol . value) pairs
        (tier1-config '()))  ;; Collect tier1 selections
    
    ;; pdftotext (always required as fallback)
    (let* ((detected (fuji--auto-detect-pdftotext))
           (pdftotext-path (if detected
                               (read-file-name 
                                (format "Path to pdftotext [%s]: " detected)
                                (file-name-directory detected)
                                detected t nil
                                (lambda (f) (or (file-directory-p f)
                                              (string-suffix-p "pdftotext" f))))
                             (read-file-name "Path to pdftotext: " nil nil t))))
      (when pdftotext-path
        (push (cons 'fuji-pdftotext-executable (expand-file-name pdftotext-path)) config-items)))
    
    
    ;; LLM extraction tool (ALWAYS configured)
    (let ((llm-tool (or (bound-and-true-p fuji-llm-extraction-tool) "marker")))
      (cond
       ;; Configure Marker
       ((string= llm-tool "marker")
        (message "")
        (message "=== Configuring Marker (LLM-based PDF Extraction) ===")
        (message "Note: Marker uses AI models for high-quality extraction with figure support.")
        (message "First run will download several GB of AI models.")
        (message "")
        (let* ((detected (fuji--auto-detect-marker))
               (marker-path (if detected
                                (read-file-name
                                 (format "Path to Marker [%s]: " detected)
                                 (file-name-directory detected)
                                 detected t nil
                                 (lambda (f) (or (file-directory-p f)
                                               (string-match-p "marker" f))))
                              (read-file-name "Path to Marker: " nil nil t))))
           (when marker-path
             (push (cons 'fuji-marker-executable (expand-file-name marker-path)) config-items))))
       
       ;; Configure Nougat (future)
       ((string= llm-tool "nougat")
        (message "")
        (message "=== Configuring Nougat (LLM-based PDF Extraction) ===")
        (message "Note: Nougat support is coming soon.")
        (message ""))
       
       ;; Other LLM tools (future)
       (t
        (message "Warning: Unknown LLM tool: %s" llm-tool))))
    
    
    
    ;; Pandoc (required for DOCX)
    (let* ((detected (fuji--auto-detect-pandoc))
           (pandoc-path (if detected
                            (read-file-name
                             (format "Path to pandoc [%s]: " detected)
                             (file-name-directory detected)
                             detected t nil
                             (lambda (f) (or (file-directory-p f)
                                           (string-suffix-p "pandoc" f))))
                          (read-file-name "Path to pandoc: " nil nil t))))
       (when pandoc-path
         (push (cons 'fuji-pandoc-executable (expand-file-name pandoc-path)) config-items)))
    
    ;; Headless Chrome (required for Web-to-PDF)
    (let* ((detected (fuji--auto-detect-chrome))
           (chrome-path (if detected
                            (read-file-name
                             (format "Path to Chrome/Chromium [%s]: " detected)
                             (file-name-directory detected)
                             detected t nil
                             (lambda (f) (file-executable-p f)))
                          (read-file-name "Path to Chrome/Chromium: " nil nil t))))
       (when (and chrome-path (not (string-empty-p chrome-path)))
         (push (cons 'fuji-chrome-executable (expand-file-name chrome-path)) config-items)))
    
    ;; Graphlit credentials (if selected)
    (when (string= (or (bound-and-true-p fuji-rag-backend-name) "") "graphlit")
      (setq config-items (append config-items (fuji-configure-graphlit))))
    
    ;; Bibliography file
    (let ((bib-file (read-file-name 
                    "Bibliography File (your main .bib file): "
                    (or (and (bound-and-true-p fuji-bibtex-file) (file-name-directory fuji-bibtex-file))
                        (expand-file-name "~/Documents/Papers/"))
                    nil t)))
      (push (cons 'fuji-bibtex-file (expand-file-name bib-file)) config-items))
    
    ;; Cache and archive directories
    (let* ((cache-dir (read-directory-name 
                       "Cache Directory: " 
                       (or (bound-and-true-p fuji-cache-directory)
                           (expand-file-name "fuji-cache/" user-emacs-directory))
                       nil t))
           (originals-name (read-string 
                            "Originals Directory Name (inside cache): " 
                            "originals"))
           (originals-dir (expand-file-name originals-name cache-dir)))
      
      ;; Expand and ensure directories exist
      (setq cache-dir (expand-file-name cache-dir))
      ;; originals-dir is already expanded against cache-dir
      
      ;; Create directories if they don't exist
      (unless (file-directory-p cache-dir)
        (make-directory cache-dir t)
        (message "Created cache directory: %s" cache-dir))
      (unless (file-directory-p originals-dir)
        (make-directory originals-dir t)
        (message "Created originals directory: %s" originals-dir))
      
      (push (cons 'fuji-cache-directory cache-dir) config-items)
      (push (cons 'fuji-originals-archive-dir originals-dir) config-items))
    
    (message "Fuji: Tool-specific configuration collected.")
    config-items))

(defun fuji-configure-graphlit ()
  "Configure Graphlit-specific settings.
Returns an alist of config items."
  (let* ((auth (condition-case nil (fuji--get-auth "graphlit") (error nil)))
         (org-id (read-string "Graphlit Organization ID: " (or (plist-get auth :user) "")))
         (secret (let ((s (read-passwd (format "Graphlit JWT Secret %s: "
                                               (if (plist-get auth :secret) 
                                                   "(leave empty to keep current)" 
                                                 "")))))
                   (if (string-empty-p s) (plist-get auth :secret) s)))
         (env-id (read-string "Graphlit Environment ID: " 
                              (or (bound-and-true-p fuji-graphlit-environment-id) "")))
         (config-items '()))
    
    (push (cons 'fuji-graphlit-environment-id env-id) config-items)
    
    (when (and (not (string-empty-p org-id)) (not (string-empty-p secret)))
      (fuji--save-auth-entry org-id secret))
    
    (fuji--register-mcp-server)
    config-items))

;;; gptel Configuration

(defun fuji-configure-gptel ()
  "Configure gptel backends for chat and vision.
Returns an alist of config items."
  (require 'gptel)
  (let* ((backends (mapcar (lambda (b) (gptel-backend-name (cdr b))) gptel--known-backends))
         (chat-backend-name (completing-read 
                             "Default Chat Backend: " backends nil nil))
         (chat-backend (gptel-get-backend chat-backend-name))
         (chat-model (completing-read "Default Chat Model: " 
                                      (gptel-backend-models chat-backend) nil nil))
         (vis-backend-name (completing-read 
                            "Vision Backend (Multimodal): " backends nil nil))
         (vis-backend (gptel-get-backend vis-backend-name))
         (vis-model (completing-read "Vision Model: " 
                                     (gptel-backend-models vis-backend) nil nil))
         (config-items '()))
    
    (push (cons 'fuji-gptel-backend chat-backend-name) config-items)
    (push (cons 'fuji-gptel-model chat-model) config-items)
    
    (unless (string-empty-p vis-backend-name)
      ;; Save as string, not symbol - this prevents "void-variable Gemini" errors
      (push (cons 'fuji-gptel-vision-backend vis-backend-name) config-items))
    (unless (string-empty-p vis-model)
      (push (cons 'fuji-gptel-vision-model vis-model) config-items))
    
    config-items))

;;; Unified Configuration Entry Point

;;;###autoload
(defun fuji-configure ()
  "Interactive configuration wizard for Fuji.
Guides through Tier 1 (tool selection) and Tier 2 (tool-specific config).
Saves all configuration to local machine-specific file."
  (interactive)
  (message "Fuji Configuration Wizard - Tier 1: Tool Selection")
  (let ((all-config '())  ;; Collect all config items
        (tier1-result (fuji-configure-tier1)))
    
    ;; Add tier1 selections to config
    (push (cons 'fuji-llm-extraction-tool (plist-get tier1-result :llm-tool)) all-config)
    (push (cons 'fuji-docx-extractor (plist-get tier1-result :docx-extractor)) all-config)
    (push (cons 'fuji-rag-backend-name (plist-get tier1-result :rag-backend)) all-config)
    
    ;; Tier 2: Tool-specific settings
    (when (y-or-n-p "Configure tool-specific settings now? ")
      (message "Fuji Configuration Wizard - Tier 2: Tool-Specific Settings")
      (setq all-config (append all-config (fuji-configure-tier2))))
    
    ;; Configure gptel backends
    (when (y-or-n-p "Configure gptel backends (chat/vision)? ")
      (setq all-config (append all-config (fuji-configure-gptel))))
    
    ;; Apply proxy settings
    (let ((proxy (read-string "HTTP Proxy (e.g. 127.0.0.1:7890, leave empty for none): "
                              (or (bound-and-true-p fuji-http-proxy) ""))))
      (push (cons 'fuji-http-proxy (if (string-empty-p proxy) nil proxy)) all-config)
      (fuji-apply-proxy))
    
    ;; Save all configuration to local file
    (fuji--save-local-config all-config)
    
    ;; Reload configuration into current session
    (fuji--load-local-config)
    (message "Fuji: Configuration saved and loaded!")
    
    (message "Fuji: Configuration complete! Run M-x fuji-validate-configuration to verify.")))

;;; Configuration Validation

;;;###autoload
(defun fuji-validate-configuration ()
  "Validate that all required tools are properly configured."
  (interactive)
  (let ((errors '())
        (warnings '()))
    
    ;; Check pdftotext (always required)
    (let ((pdftotext (fuji--auto-detect-pdftotext)))
      (if (and pdftotext (file-executable-p pdftotext))
          (message "✓ pdftotext: %s" pdftotext)
        (push "pdftotext not found or not executable (required)" errors)))
    
    
    ;; Check LLM extraction tool (ALWAYS configured)
    (let ((llm-tool (or (bound-and-true-p fuji-llm-extraction-tool) "marker")))
      (cond
       ((string= llm-tool "marker")
        (let ((marker (fuji--auto-detect-marker)))
          (if (and marker (file-executable-p marker))
              (message "✓ Marker (LLM tool): %s" marker)
            (push "Marker (LLM tool) not found or not executable" errors))))
       ((string= llm-tool "nougat")
        (push "Nougat selected but not yet supported" warnings))
       (t
        (push (format "Unknown LLM tool selected: %s" llm-tool) errors))))
    
    
    
    ;; Check pandoc
    (let ((pandoc (fuji--auto-detect-pandoc)))
      (if (and pandoc (file-executable-p pandoc))
          (message "✓ pandoc: %s" pandoc)
        (push "pandoc not found or not executable (required for DOCX/EPUB)" warnings)))

    ;; Check Chrome
    (let ((chrome (fuji--auto-detect-chrome)))
      (if (and chrome (file-executable-p chrome))
          (message "✓ Chrome: %s" chrome)
        (push "Google Chrome/Chromium not found (required for Web URL support)" warnings)))
    
    ;; Check Graphlit if selected
    (when (string= (or (bound-and-true-p fuji-rag-backend-name) "") "graphlit")
      (if (and (bound-and-true-p fuji-graphlit-environment-id)
               (condition-case nil (fuji--get-auth "graphlit") (error nil)))
          (message "✓ Graphlit credentials configured")
        (push "Graphlit selected but credentials not configured" errors)))
    
    ;; Check cache directory
    (if (and (bound-and-true-p fuji-cache-directory)
             (or (file-directory-p fuji-cache-directory)
                 (yes-or-no-p (format "Cache directory %s does not exist. Create it? " 
                                      fuji-cache-directory))))
        (progn
          (unless (file-directory-p fuji-cache-directory)
            (make-directory fuji-cache-directory t))
          (message "✓ Cache directory: %s" fuji-cache-directory))
      (push "Cache directory not configured or creation cancelled" errors))
    
    ;; Display results
    (let ((msg (concat
                (when errors
                  (concat "❌ ERRORS:\n" (mapconcat (lambda (e) (concat "  - " e)) errors "\n") "\n\n"))
                (when warnings
                  (concat "⚠ WARNINGS:\n" (mapconcat (lambda (w) (concat "  - " w)) warnings "\n") "\n\n"))
                (unless (or errors warnings)
                  "✅ All configuration checks passed!"))))
      (if (or errors warnings)
          (display-message-or-buffer msg "*Fuji Configuration Validation*")
        (message "%s" msg))
      (null errors))))

(provide 'fuji-configure)
;;; fuji-configure.el ends here
