#!/bin/bash
# Script to reload fuji in Emacs daemon

echo "=== Reloading Fuji in Emacs Daemon ==="
echo ""
echo "Option 1: Restart Emacs Daemon (Recommended)"
echo "  1. Stop daemon: emacsclient -e '(kill-emacs)'"
echo "  2. Start daemon: emacs --daemon"
echo "  3. Connect: emacsclient -c"
echo ""
echo "Option 2: Force Reload in Current Session"
echo "  Execute in Emacs:"
echo "  M-x eval-expression RET"
echo "  (progn"
echo "    (unload-feature 'fuji-configure t)"
echo "    (unload-feature 'fuji t)"
echo "    (load-file \"/home/ruan/Repositories/EmacsPaperreadingWorkflowAtGithub/fuji-configure.el\")"
echo "    (load-file \"/home/ruan/Repositories/EmacsPaperreadingWorkflowAtGithub/fuji.el\")"
echo "    (message \"Fuji reloaded\"))"
echo ""
echo "Option 3: Temporary Workaround"
echo "  Comment out the fuji--load-local-config call temporarily"
echo "  Then run M-x fuji-configure to create the config file"
echo "  Then uncomment and reload"
echo ""
